<a href="https://colab.research.google.com/github/SrikrshnaP/DeepLearning-FirstCourse/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This notebook has the most basic and fundamental concepts of TensorFlow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
#Createing tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#Check dimension of Vector
vector.ndim

1

In [6]:
# Creating a matrix with more than one dimention
matrix = tf.constant ([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
#Check the number of dimentions for the matrix
matrix.ndim

2

In [8]:
#Create another matrix
another_matrix = tf.constant ([[1., 2.], 
                               [3., 4.], 
                               [5., 6.]], dtype = tf.float16)

In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [10]:
#Number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a Tensor
tensor = tf.constant ([[[1, 2, 3],
                        [4, 5, 6]], 
                        [[6, 7,8 ], 
                         [3, 4, 6]], 
                       [[1, 2, 4], 
                        [6, 5, 8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [3, 4, 6]],

       [[1, 2, 4],
        [6, 5, 8]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we have created so far:

* Scalar - a single Number
* Vector - a number with direction
* Matrix - a 2D array of numbers
* Tensor - an n-dimentional array of numbers 

In [13]:
#creating tensors with 'tf.variable'
changeable_tensor = tf.Variable ([10, 7])
unchangeable_tensor = tf.constant ([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
#unchangeable_tensor cannot be changed as it is declared as tf."constant"

In [16]:
#Creating Random Tensors
#Random tensors - Tensors of arbitrary size which contain random numbers
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal (shape = (3, 2))

In [17]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random2 = tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [20]:
random3 = tf.random.Generator.from_seed(7)
random3 = random3.normal (shape = (3, 2))
random3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

 Shuffle the order of the elements in a tensor

In [21]:
#shuffle a tensor (Value-able to shuffle data)
not_shuffled = tf.constant([[10, 7],
                            [1, 2],
                            [4, 5]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10,  7],
       [ 4,  5]], dtype=int32)>

In [22]:
shuffled1 = tf.random.shuffle(not_shuffled)
shuffled1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 1,  2]], dtype=int32)>

In [23]:
shuffled2 = tf.random.shuffle(not_shuffled, seed = 42)
shuffled2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [24]:
shuffled3 = tf.random.shuffle(not_shuffled, seed = 42)
shuffled3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [25]:
tf.random.set_seed(42) # Global seed 
tf.random.shuffle(not_shuffled)
#The seeds used along with the suffle command are operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 4,  5],
       [10,  7]], dtype=int32)>

Other ways of making a tensor

In [26]:
#making a tensor of only ones
tf.ones(shape=(2, 3), dtype = tf.int64) #default - flaot type

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [27]:
#tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [28]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)

A = tf.constant(numpy_A, shape = [2, 4, 3])

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

Getting information from Tensors

In [29]:
# You can create Tensor objects with the `tf.constant` function:
x = tf.constant([[1, 2, 3, 4 ,5]])
# You can create Tensor objects only consisting of 1s with the `tf.ones` function:
y = tf.ones((1,5))
# You can create Tensor objects only consisting of 0s with the `tf.zeros` function:
z = tf.zeros((1,5))
# You can use the `tf.range()` function to create Tensor objects:
q = tf.range(start=1, limit=6, delta=1)

print(x)
print(y)
print(z)
print(q)

tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor([[1. 1. 1. 1. 1.]], shape=(1, 5), dtype=float32)
tf.Tensor([[0. 0. 0. 0. 0.]], shape=(1, 5), dtype=float32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [30]:
#RNG - Random Number Generation
g1=tf.random.get_global_generator()
print(g1)
print("\n")
g1.normal(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.9884903 ,  0.5815689 ,  2.481078  ],
       [ 0.4512945 , -0.5289913 , -0.77783144]], dtype=float32)>

In [31]:
g2 = tf.random.Generator.from_seed(42)
print(g2.normal(shape=[2, 3]))

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193763 -1.8107855 ]], shape=(2, 3), dtype=float32)


In [32]:
g3 = tf.random.Generator.from_seed(42, alg='philox')
g3.normal(shape=[2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [33]:
g4 = tf.random.Generator.from_non_deterministic_state()
g4.normal(shape=[2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.01860616,  0.8557417 , -0.5149185 ],
       [-0.9604065 , -0.39236802, -0.37581414]], dtype=float32)>

In [34]:
g = tf.random.Generator.from_seed(1)
print(g.normal([]))
new_gs = g.split(3)
for new_g in new_gs:
  print(new_g.normal([]))
print(g.normal([]))

tf.Tensor(0.43842274, shape=(), dtype=float32)
tf.Tensor(2.536413, shape=(), dtype=float32)
tf.Tensor(0.33186463, shape=(), dtype=float32)
tf.Tensor(-0.07144657, shape=(), dtype=float32)
tf.Tensor(-0.79253083, shape=(), dtype=float32)


tf.random.set_seed
Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [35]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
#Gives different values everytime it is run

tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [36]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
# retains the same value every it is run

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [37]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

#The reason we get 'A2' instead 'A1' on the second call of tf.random.uniform above is because the same tf.random.uniform kernel (i.e. internal representation) is used by TensorFlow for all calls of it with the same arguments, and the kernel maintains an internal counter which is incremented every time it is executed, generating different results.

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [38]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [39]:
#When multiple identical random ops are wrapped in a tf.function, their behaviors change because the ops no long share the same counter. For example:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


In [40]:
print(tf.ones([2, 2]))
print(tf.zeros([2, 2]))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [41]:
#converting Numpy arrays into tensors
import numpy as np
numpy_A = np.arange (1, 25, dtype = np.int32)

A = tf.constant(numpy_A, shape = (2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Getting information from Tensors
* Shape
* Rank
* Axis or Dimension
* Size

In [42]:
#Create of rank 4 Dimensions
rank_4_tensor = tf.zeros (shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [44]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [45]:
2*3*4*5

120

In [46]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) 
# .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [47]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [48]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [49]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
print(rank_2_tensor)
print("\n")
print(rank_2_tensor.shape, rank_2_tensor.ndim)
print("\n")
# Get the last item of each row
rank_2_tensor[:, -1]

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


(2, 2) 2




<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [50]:
#Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>