<a href="https://colab.research.google.com/github/SrikrshnaP/DeepLearning-FirstCourse/blob/main/00_TF_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#This notebook has the most basic and fundamental concepts of TensorFlow

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
#Createing tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check dimension of Vector
vector.ndim

1

In [ ]:
# Creating a matrix with more than one dimention
matrix = tf.constant ([[1, 2], [3, 4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
#Check the number of dimentions for the matrix
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant ([[1., 2.], 
                               [3., 4.], 
                               [5., 6.]], dtype = tf.float16)

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [ ]:
#Number of dimensions of another_matrix
another_matrix.ndim

2

In [ ]:
# Let's create a Tensor
tensor = tf.constant ([[[1, 2, 3],
                        [4, 5, 6]], 
                        [[6, 7,8 ], 
                         [3, 4, 6]], 
                       [[1, 2, 4], 
                        [6, 5, 8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 7, 8],
        [3, 4, 6]],

       [[1, 2, 4],
        [6, 5, 8]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we have created so far:

* Scalar - a single Number
* Vector - a number with direction
* Matrix - a 2D array of numbers
* Tensor - an n-dimentional array of numbers 

In [ ]:
#creating tensors with 'tf.variable'
changeable_tensor = tf.Variable ([10, 7])
unchangeable_tensor = tf.constant ([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#unchangeable_tensor cannot be changed as it is declared as tf."constant"

In [ ]:
#Creating Random Tensors
#Random tensors - Tensors of arbitrary size which contain random numbers
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal (shape = (3, 2))

In [ ]:
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(42)
random2=random2.normal(shape=(3, 2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [ ]:
random3 = tf.random.Generator.from_seed(7)
random3 = random3.normal (shape = (3, 2))
random3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

 Shuffle the order of the elements in a tensor

In [ ]:
#shuffle a tensor (Value-able to shuffle data)
not_shuffled = tf.constant([[10, 7],
                            [1, 2],
                            [4, 5]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 4,  5],
       [10,  7]], dtype=int32)>

In [ ]:
shuffled1 = tf.random.shuffle(not_shuffled)
shuffled1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [ ]:
shuffled2 = tf.random.shuffle(not_shuffled, seed = 42)
shuffled2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [ ]:
shuffled3 = tf.random.shuffle(not_shuffled, seed = 42)
shuffled3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 4,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # Global seed 
tf.random.shuffle(not_shuffled)
#The seeds used along with the suffle command are operation-level seeds

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 4,  5],
       [10,  7]], dtype=int32)>

Other ways of making a tensor

In [39]:
#making a tensor of only ones
tf.ones(shape=(2, 3), dtype = tf.int64) #default - flaot type

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [40]:
#tensor of all zeros
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [42]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)

A = tf.constant(numpy_A, shape = [2, 4, 3])

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

Getting information from Tensors